// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlP9HwqRbyabO0X7XIkKNvUcO2Bwtu278',
    appId: '1:930252220349:web:c7addc21a05b6ba8c494d4',
    messagingSenderId: '930252220349',
    projectId: 'quiz-e4e86',
    authDomain: 'quiz-e4e86.firebaseapp.com',
    databaseURL: 'https://quiz-e4e86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-e4e86.firebasestorage.app',
    measurementId: 'G-BRB78QRF39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRPtlq5YpIlioex_W5wsZhWMjFtvbA1pw',
    appId: '1:930252220349:android:c6b7d17721ea8512c494d4',
    messagingSenderId: '930252220349',
    projectId: 'quiz-e4e86',
    databaseURL: 'https://quiz-e4e86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-e4e86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAwR2Snyz5sH7g86gDORH_vAcLoAcYjY',
    appId: '1:930252220349:ios:bcdb7d1301269d4ec494d4',
    messagingSenderId: '930252220349',
    projectId: 'quiz-e4e86',
    databaseURL: 'https://quiz-e4e86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-e4e86.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtAwR2Snyz5sH7g86gDORH_vAcLoAcYjY',
    appId: '1:930252220349:ios:bcdb7d1301269d4ec494d4',
    messagingSenderId: '930252220349',
    projectId: 'quiz-e4e86',
    databaseURL: 'https://quiz-e4e86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-e4e86.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlP9HwqRbyabO0X7XIkKNvUcO2Bwtu278',
    appId: '1:930252220349:web:f6990203078c2aa5c494d4',
    messagingSenderId: '930252220349',
    projectId: 'quiz-e4e86',
    authDomain: 'quiz-e4e86.firebaseapp.com',
    databaseURL: 'https://quiz-e4e86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-e4e86.firebasestorage.app',
    measurementId: 'G-MSNTXK635P',
  );
}
